name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  INPUT_GITHUB_EMAIL: github-actions[bot]@users.noreply.github.com
  INPUT_GITHUB_USERNAME: github-actions[bot]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          yarn
          yarn build

      - name: Config
        run: |
          git config --global user.email "$INPUT_GITHUB_EMAIL"
          git config --global user.name "$INPUT_GITHUB_USERNAME"
          yarn config set version-git-message "%s"

      - name: Update version
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          git checkout "$tag"
          yarn version --new-version "$tag"
          git tag -d "v$tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          push_only_tags: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release upload "$tag" \
            main.js manifest.json styles.css
